# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo_server.proto',
  package='demo_server',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  serialized_pb=b'\n\x11\x64\x65mo_server.proto\x12\x0b\x64\x65mo_server\"$\n\x12\x44\x65moServiceRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x04\"%\n\x13\x44\x65moServiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\x04\x32X\n\x0b\x44\x65moService\x12I\n\x04\x66unc\x12\x1f.demo_server.DemoServiceRequest\x1a .demo_server.DemoServiceResponseB\x03\x80\x01\x00\x62\x06proto3'
)




_DEMOSERVICEREQUEST = _descriptor.Descriptor(
  name='DemoServiceRequest',
  full_name='demo_server.DemoServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='demo_server.DemoServiceRequest.req_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=70,
)


_DEMOSERVICERESPONSE = _descriptor.Descriptor(
  name='DemoServiceResponse',
  full_name='demo_server.DemoServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='demo_server.DemoServiceResponse.status', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['DemoServiceRequest'] = _DEMOSERVICEREQUEST
DESCRIPTOR.message_types_by_name['DemoServiceResponse'] = _DEMOSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoServiceRequest = _reflection.GeneratedProtocolMessageType('DemoServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEMOSERVICEREQUEST,
  '__module__' : 'demo_server_pb2'
  # @@protoc_insertion_point(class_scope:demo_server.DemoServiceRequest)
  })
_sym_db.RegisterMessage(DemoServiceRequest)

DemoServiceResponse = _reflection.GeneratedProtocolMessageType('DemoServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEMOSERVICERESPONSE,
  '__module__' : 'demo_server_pb2'
  # @@protoc_insertion_point(class_scope:demo_server.DemoServiceResponse)
  })
_sym_db.RegisterMessage(DemoServiceResponse)


DESCRIPTOR._options = None

_DEMOSERVICE = _descriptor.ServiceDescriptor(
  name='DemoService',
  full_name='demo_server.DemoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=111,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='func',
    full_name='demo_server.DemoService.func',
    index=0,
    containing_service=None,
    input_type=_DEMOSERVICEREQUEST,
    output_type=_DEMOSERVICERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMOSERVICE)

DESCRIPTOR.services_by_name['DemoService'] = _DEMOSERVICE

# @@protoc_insertion_point(module_scope)
