# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_server_pb2 as demo__server__pb2


class DemoServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.func = channel.unary_unary(
                '/demo_server.DemoService/func',
                request_serializer=demo__server__pb2.DemoServiceRequest.SerializeToString,
                response_deserializer=demo__server__pb2.DemoServiceResponse.FromString,
                )


class DemoServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def func(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'func': grpc.unary_unary_rpc_method_handler(
                    servicer.func,
                    request_deserializer=demo__server__pb2.DemoServiceRequest.FromString,
                    response_serializer=demo__server__pb2.DemoServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo_server.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def func(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo_server.DemoService/func',
            demo__server__pb2.DemoServiceRequest.SerializeToString,
            demo__server__pb2.DemoServiceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
