# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import feature_service_pb2 as feature__service__pb2


class FeatureServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_feature = channel.unary_unary(
                '/feature_service.FeatureService/get_feature',
                request_serializer=feature__service__pb2.FeatureRequest.SerializeToString,
                response_deserializer=feature__service__pb2.FeatureResponse.FromString,
                )


class FeatureServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def get_feature(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_feature': grpc.unary_unary_rpc_method_handler(
                    servicer.get_feature,
                    request_deserializer=feature__service__pb2.FeatureRequest.FromString,
                    response_serializer=feature__service__pb2.FeatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feature_service.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeatureService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def get_feature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feature_service.FeatureService/get_feature',
            feature__service__pb2.FeatureRequest.SerializeToString,
            feature__service__pb2.FeatureResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
