# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2
import item_info_pb2 as item__info__pb2
import rank_pb2 as rank__pb2
import recall_pb2 as recall__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature_service.proto',
  package='feature_service',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  serialized_pb=b'\n\x15\x66\x65\x61ture_service.proto\x12\x0f\x66\x65\x61ture_service\x1a\x0fuser_info.proto\x1a\x0fitem_info.proto\x1a\nrank.proto\x1a\x0crecall.proto\"\xc8\x01\n\x0e\x46\x65\x61tureRequest\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.feature_service.FeatureRequest.Type\x12.\n\x0crank_request\x18\x02 \x01(\x0b\x32\x18.rank_server.RankRequest\x12\x34\n\x0erecall_request\x18\x03 \x01(\x0b\x32\x1c.recall_server.RecallRequest\"\x1c\n\x04Type\x12\x08\n\x04RANK\x10\x00\x12\n\n\x06RECALL\x10\x01\"\x91\x02\n\x06\x46SRank\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1d.feature_service.FSRank.Error\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12)\n\x0citem_content\x18\x03 \x03(\x0b\x32\x13.item_info.ItemInfo\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"a\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fVALUE_NOT_EXIST\x10\x01\x12\x0c\n\x08IDM_FAIL\x10\x02\x12\x11\n\rINTERIOR_FAIL\x10\x03\x12\x14\n\x10PLUGIN_EXEC_FAIL\x10\x04\"\x94\x01\n\x08\x46SRecall\x12.\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1f.feature_service.FSRecall.Error\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12\x0b\n\x03nid\x18\x03 \x03(\t\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xc6\x01\n\x0f\x46\x65\x61tureResponse\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.feature_service.FeatureResponse.Type\x12-\n\x0crank_feature\x18\x02 \x01(\x0b\x32\x17.feature_service.FSRank\x12\x31\n\x0erecall_feature\x18\x03 \x01(\x0b\x32\x19.feature_service.FSRecall\"\x1c\n\x04Type\x12\x08\n\x04RANK\x10\x00\x12\n\n\x06RECALL\x10\x01\x32\x62\n\x0e\x46\x65\x61tureService\x12P\n\x0bget_feature\x12\x1f.feature_service.FeatureRequest\x1a .feature_service.FeatureResponseB\x03\x80\x01\x00\x62\x06proto3'
  ,
  dependencies=[user__info__pb2.DESCRIPTOR,item__info__pb2.DESCRIPTOR,rank__pb2.DESCRIPTOR,recall__pb2.DESCRIPTOR,])



_FEATUREREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='feature_service.FeatureRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=275,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_FEATUREREQUEST_TYPE)

_FSRANK_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='feature_service.FSRank.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_NOT_EXIST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDM_FAIL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERIOR_FAIL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLUGIN_EXEC_FAIL', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=482,
  serialized_end=579,
)
_sym_db.RegisterEnumDescriptor(_FSRANK_STATUS)

_FEATURERESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='feature_service.FeatureResponse.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=275,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_FEATURERESPONSE_TYPE)


_FEATUREREQUEST = _descriptor.Descriptor(
  name='FeatureRequest',
  full_name='feature_service.FeatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='feature_service.FeatureRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_request', full_name='feature_service.FeatureRequest.rank_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recall_request', full_name='feature_service.FeatureRequest.recall_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATUREREQUEST_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=303,
)


_FSRANK_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='feature_service.FSRank.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='feature_service.FSRank.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='feature_service.FSRank.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=480,
)

_FSRANK = _descriptor.Descriptor(
  name='FSRank',
  full_name='feature_service.FSRank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='feature_service.FSRank.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='feature_service.FSRank.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_content', full_name='feature_service.FSRank.item_content', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FSRANK_ERROR, ],
  enum_types=[
    _FSRANK_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=579,
)


_FSRECALL_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='feature_service.FSRecall.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='feature_service.FSRecall.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='feature_service.FSRecall.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=480,
)

_FSRECALL = _descriptor.Descriptor(
  name='FSRecall',
  full_name='feature_service.FSRecall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='feature_service.FSRecall.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='feature_service.FSRecall.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nid', full_name='feature_service.FSRecall.nid', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FSRECALL_ERROR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=730,
)


_FEATURERESPONSE = _descriptor.Descriptor(
  name='FeatureResponse',
  full_name='feature_service.FeatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='feature_service.FeatureResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_feature', full_name='feature_service.FeatureResponse.rank_feature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recall_feature', full_name='feature_service.FeatureResponse.recall_feature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURERESPONSE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=931,
)

_FEATUREREQUEST.fields_by_name['type'].enum_type = _FEATUREREQUEST_TYPE
_FEATUREREQUEST.fields_by_name['rank_request'].message_type = rank__pb2._RANKREQUEST
_FEATUREREQUEST.fields_by_name['recall_request'].message_type = recall__pb2._RECALLREQUEST
_FEATUREREQUEST_TYPE.containing_type = _FEATUREREQUEST
_FSRANK_ERROR.containing_type = _FSRANK
_FSRANK.fields_by_name['error'].message_type = _FSRANK_ERROR
_FSRANK.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
_FSRANK.fields_by_name['item_content'].message_type = item__info__pb2._ITEMINFO
_FSRANK_STATUS.containing_type = _FSRANK
_FSRECALL_ERROR.containing_type = _FSRECALL
_FSRECALL.fields_by_name['error'].message_type = _FSRECALL_ERROR
_FSRECALL.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
_FEATURERESPONSE.fields_by_name['type'].enum_type = _FEATURERESPONSE_TYPE
_FEATURERESPONSE.fields_by_name['rank_feature'].message_type = _FSRANK
_FEATURERESPONSE.fields_by_name['recall_feature'].message_type = _FSRECALL
_FEATURERESPONSE_TYPE.containing_type = _FEATURERESPONSE
DESCRIPTOR.message_types_by_name['FeatureRequest'] = _FEATUREREQUEST
DESCRIPTOR.message_types_by_name['FSRank'] = _FSRANK
DESCRIPTOR.message_types_by_name['FSRecall'] = _FSRECALL
DESCRIPTOR.message_types_by_name['FeatureResponse'] = _FEATURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREREQUEST,
  '__module__' : 'feature_service_pb2'
  # @@protoc_insertion_point(class_scope:feature_service.FeatureRequest)
  })
_sym_db.RegisterMessage(FeatureRequest)

FSRank = _reflection.GeneratedProtocolMessageType('FSRank', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _FSRANK_ERROR,
    '__module__' : 'feature_service_pb2'
    # @@protoc_insertion_point(class_scope:feature_service.FSRank.Error)
    })
  ,
  'DESCRIPTOR' : _FSRANK,
  '__module__' : 'feature_service_pb2'
  # @@protoc_insertion_point(class_scope:feature_service.FSRank)
  })
_sym_db.RegisterMessage(FSRank)
_sym_db.RegisterMessage(FSRank.Error)

FSRecall = _reflection.GeneratedProtocolMessageType('FSRecall', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _FSRECALL_ERROR,
    '__module__' : 'feature_service_pb2'
    # @@protoc_insertion_point(class_scope:feature_service.FSRecall.Error)
    })
  ,
  'DESCRIPTOR' : _FSRECALL,
  '__module__' : 'feature_service_pb2'
  # @@protoc_insertion_point(class_scope:feature_service.FSRecall)
  })
_sym_db.RegisterMessage(FSRecall)
_sym_db.RegisterMessage(FSRecall.Error)

FeatureResponse = _reflection.GeneratedProtocolMessageType('FeatureResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEATURERESPONSE,
  '__module__' : 'feature_service_pb2'
  # @@protoc_insertion_point(class_scope:feature_service.FeatureResponse)
  })
_sym_db.RegisterMessage(FeatureResponse)


DESCRIPTOR._options = None

_FEATURESERVICE = _descriptor.ServiceDescriptor(
  name='FeatureService',
  full_name='feature_service.FeatureService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=933,
  serialized_end=1031,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_feature',
    full_name='feature_service.FeatureService.get_feature',
    index=0,
    containing_service=None,
    input_type=_FEATUREREQUEST,
    output_type=_FEATURERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATURESERVICE)

DESCRIPTOR.services_by_name['FeatureService'] = _FEATURESERVICE

# @@protoc_insertion_point(module_scope)
