# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gcms_server_pb2 as gcms__server__pb2


class GcmsStub(object):
    """The gcms service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertItemInfo = channel.unary_unary(
                '/gcms_server.Gcms/InsertItemInfo',
                request_serializer=gcms__server__pb2.GcmsInsertItemInfoRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsInsertItemInfoReply.FromString,
                )
        self.UpdateItemInfo = channel.unary_unary(
                '/gcms_server.Gcms/UpdateItemInfo',
                request_serializer=gcms__server__pb2.GcmsUpdateItemInfoRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsUpdateItemInfoReply.FromString,
                )
        self.GetItemInfo = channel.unary_unary(
                '/gcms_server.Gcms/GetItemInfo',
                request_serializer=gcms__server__pb2.GcmsGetItemInfoRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsGetItemInfoReply.FromString,
                )
        self.DeleteItemInfo = channel.unary_unary(
                '/gcms_server.Gcms/DeleteItemInfo',
                request_serializer=gcms__server__pb2.GcmsDeleteItemInfoRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsDeleteItemInfoReply.FromString,
                )
        self.GetItemTags = channel.unary_unary(
                '/gcms_server.Gcms/GetItemTags',
                request_serializer=gcms__server__pb2.GcmsGetItemTagsRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsGetItemTagsReply.FromString,
                )
        self.IncItemPvs = channel.unary_unary(
                '/gcms_server.Gcms/IncItemPvs',
                request_serializer=gcms__server__pb2.GcmsIncItemPvsRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsIncItemPvsReply.FromString,
                )
        self.GetItemPvs = channel.unary_unary(
                '/gcms_server.Gcms/GetItemPvs',
                request_serializer=gcms__server__pb2.GcmsGetItemPvsRequest.SerializeToString,
                response_deserializer=gcms__server__pb2.GcmsGetItemPvsReply.FromString,
                )


class GcmsServicer(object):
    """The gcms service definition.
    """

    def InsertItemInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItemInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemTags(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncItemPvs(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemPvs(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GcmsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertItemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertItemInfo,
                    request_deserializer=gcms__server__pb2.GcmsInsertItemInfoRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsInsertItemInfoReply.SerializeToString,
            ),
            'UpdateItemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemInfo,
                    request_deserializer=gcms__server__pb2.GcmsUpdateItemInfoRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsUpdateItemInfoReply.SerializeToString,
            ),
            'GetItemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemInfo,
                    request_deserializer=gcms__server__pb2.GcmsGetItemInfoRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsGetItemInfoReply.SerializeToString,
            ),
            'DeleteItemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItemInfo,
                    request_deserializer=gcms__server__pb2.GcmsDeleteItemInfoRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsDeleteItemInfoReply.SerializeToString,
            ),
            'GetItemTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemTags,
                    request_deserializer=gcms__server__pb2.GcmsGetItemTagsRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsGetItemTagsReply.SerializeToString,
            ),
            'IncItemPvs': grpc.unary_unary_rpc_method_handler(
                    servicer.IncItemPvs,
                    request_deserializer=gcms__server__pb2.GcmsIncItemPvsRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsIncItemPvsReply.SerializeToString,
            ),
            'GetItemPvs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemPvs,
                    request_deserializer=gcms__server__pb2.GcmsGetItemPvsRequest.FromString,
                    response_serializer=gcms__server__pb2.GcmsGetItemPvsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gcms_server.Gcms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gcms(object):
    """The gcms service definition.
    """

    @staticmethod
    def InsertItemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/InsertItemInfo',
            gcms__server__pb2.GcmsInsertItemInfoRequest.SerializeToString,
            gcms__server__pb2.GcmsInsertItemInfoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/UpdateItemInfo',
            gcms__server__pb2.GcmsUpdateItemInfoRequest.SerializeToString,
            gcms__server__pb2.GcmsUpdateItemInfoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/GetItemInfo',
            gcms__server__pb2.GcmsGetItemInfoRequest.SerializeToString,
            gcms__server__pb2.GcmsGetItemInfoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/DeleteItemInfo',
            gcms__server__pb2.GcmsDeleteItemInfoRequest.SerializeToString,
            gcms__server__pb2.GcmsDeleteItemInfoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/GetItemTags',
            gcms__server__pb2.GcmsGetItemTagsRequest.SerializeToString,
            gcms__server__pb2.GcmsGetItemTagsReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncItemPvs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/IncItemPvs',
            gcms__server__pb2.GcmsIncItemPvsRequest.SerializeToString,
            gcms__server__pb2.GcmsIncItemPvsReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemPvs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcms_server.Gcms/GetItemPvs',
            gcms__server__pb2.GcmsGetItemPvsRequest.SerializeToString,
            gcms__server__pb2.GcmsGetItemPvsReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
