# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rank_pb2 as rank__pb2


class RankServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rank_predict = channel.unary_unary(
                '/rank_server.RankService/rank_predict',
                request_serializer=rank__pb2.RankRequest.SerializeToString,
                response_deserializer=rank__pb2.RankResponse.FromString,
                )


class RankServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def rank_predict(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'rank_predict': grpc.unary_unary_rpc_method_handler(
                    servicer.rank_predict,
                    request_deserializer=rank__pb2.RankRequest.FromString,
                    response_serializer=rank__pb2.RankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rank_server.RankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RankService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def rank_predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rank_server.RankService/rank_predict',
            rank__pb2.RankRequest.SerializeToString,
            rank__pb2.RankResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
