# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_info_pb2 as item__info__pb2
import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  serialized_pb=b'\n\x0csample.proto\x12\x06sample\x1a\x0fitem_info.proto\x1a\x0fuser_info.proto\"7\n\rSampleContext\x12&\n\titem_info\x18\x01 \x01(\x0b\x32\x13.item_info.ItemInfo\"\x81\x01\n\x06Sample\x12\r\n\x05logid\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12&\n\tuser_info\x18\x03 \x01(\x0b\x32\x13.user_info.UserInfo\x12-\n\x0esample_context\x18\x04 \x03(\x0b\x32\x15.sample.SampleContextB\x03\x80\x01\x00\x62\x06proto3'
  ,
  dependencies=[item__info__pb2.DESCRIPTOR,user__info__pb2.DESCRIPTOR,])




_SAMPLECONTEXT = _descriptor.Descriptor(
  name='SampleContext',
  full_name='sample.SampleContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_info', full_name='sample.SampleContext.item_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=113,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='sample.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logid', full_name='sample.Sample.logid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sample.Sample.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='sample.Sample.user_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_context', full_name='sample.Sample.sample_context', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=245,
)

_SAMPLECONTEXT.fields_by_name['item_info'].message_type = item__info__pb2._ITEMINFO
_SAMPLE.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
_SAMPLE.fields_by_name['sample_context'].message_type = _SAMPLECONTEXT
DESCRIPTOR.message_types_by_name['SampleContext'] = _SAMPLECONTEXT
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleContext = _reflection.GeneratedProtocolMessageType('SampleContext', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLECONTEXT,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.SampleContext)
  })
_sym_db.RegisterMessage(SampleContext)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.Sample)
  })
_sym_db.RegisterMessage(Sample)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
