# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: um_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_info_pb2 as user__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='um_server.proto',
  package='um_server',
  syntax='proto3',
  serialized_options=b'\200\001\000',
  serialized_pb=b'\n\x0fum_server.proto\x12\tum_server\x1a\x0fuser_info.proto\"6\n\x10UserModelRequest\x12\x11\n\tsearch_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x85\x02\n\x11UserModelResponse\x12\x31\n\x05\x65rror\x18\x01 \x01(\x0b\x32\".um_server.UserModelResponse.Error\x12&\n\tuser_info\x18\x02 \x01(\x0b\x32\x13.user_info.UserInfo\x12\x33\n\x06status\x18\x03 \x01(\x0e\x32#.um_server.UserModelResponse.Status\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\";\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fVALUE_NOT_EXIST\x10\x01\x12\x0f\n\x0bSEARCH_FAIL\x10\x02\"K\n\rUpdateRequest\x12\x11\n\tsearch_id\x18\x01 \x01(\t\x12\'\n\nuser_infos\x18\x02 \x03(\x0b\x32\x13.user_info.UserInfo\"\xd8\x01\n\x0eUpdateResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .um_server.UpdateResponse.Status\x12.\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1f.um_server.UpdateResponse.Error\x12\x0f\n\x07success\x18\x03 \x03(\t\x1a#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\".\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x12\r\n\tPART_SUCC\x10\x02\x32\x96\x01\n\x10UserModelService\x12\x43\n\x06search\x12\x1b.um_server.UserModelRequest\x1a\x1c.um_server.UserModelResponse\x12=\n\x06update\x12\x18.um_server.UpdateRequest\x1a\x19.um_server.UpdateResponseB\x03\x80\x01\x00\x62\x06proto3'
  ,
  dependencies=[user__info__pb2.DESCRIPTOR,])



_USERMODELRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='um_server.UserModelResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_NOT_EXIST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH_FAIL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=306,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_USERMODELRESPONSE_STATUS)

_UPDATERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='um_server.UpdateResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PART_SUCC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=615,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_UPDATERESPONSE_STATUS)


_USERMODELREQUEST = _descriptor.Descriptor(
  name='UserModelRequest',
  full_name='um_server.UserModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_id', full_name='um_server.UserModelRequest.search_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='um_server.UserModelRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=101,
)


_USERMODELRESPONSE_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='um_server.UserModelResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='um_server.UserModelResponse.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='um_server.UserModelResponse.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=304,
)

_USERMODELRESPONSE = _descriptor.Descriptor(
  name='UserModelResponse',
  full_name='um_server.UserModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='um_server.UserModelResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='um_server.UserModelResponse.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='um_server.UserModelResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERMODELRESPONSE_ERROR, ],
  enum_types=[
    _USERMODELRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=365,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='um_server.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_id', full_name='um_server.UpdateRequest.search_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_infos', full_name='um_server.UpdateRequest.user_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=442,
)


_UPDATERESPONSE_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='um_server.UpdateResponse.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='um_server.UpdateResponse.Error.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='um_server.UpdateResponse.Error.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=304,
)

_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='um_server.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='um_server.UpdateResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='um_server.UpdateResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='um_server.UpdateResponse.success', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATERESPONSE_ERROR, ],
  enum_types=[
    _UPDATERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=661,
)

_USERMODELRESPONSE_ERROR.containing_type = _USERMODELRESPONSE
_USERMODELRESPONSE.fields_by_name['error'].message_type = _USERMODELRESPONSE_ERROR
_USERMODELRESPONSE.fields_by_name['user_info'].message_type = user__info__pb2._USERINFO
_USERMODELRESPONSE.fields_by_name['status'].enum_type = _USERMODELRESPONSE_STATUS
_USERMODELRESPONSE_STATUS.containing_type = _USERMODELRESPONSE
_UPDATEREQUEST.fields_by_name['user_infos'].message_type = user__info__pb2._USERINFO
_UPDATERESPONSE_ERROR.containing_type = _UPDATERESPONSE
_UPDATERESPONSE.fields_by_name['status'].enum_type = _UPDATERESPONSE_STATUS
_UPDATERESPONSE.fields_by_name['error'].message_type = _UPDATERESPONSE_ERROR
_UPDATERESPONSE_STATUS.containing_type = _UPDATERESPONSE
DESCRIPTOR.message_types_by_name['UserModelRequest'] = _USERMODELREQUEST
DESCRIPTOR.message_types_by_name['UserModelResponse'] = _USERMODELRESPONSE
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserModelRequest = _reflection.GeneratedProtocolMessageType('UserModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERMODELREQUEST,
  '__module__' : 'um_server_pb2'
  # @@protoc_insertion_point(class_scope:um_server.UserModelRequest)
  })
_sym_db.RegisterMessage(UserModelRequest)

UserModelResponse = _reflection.GeneratedProtocolMessageType('UserModelResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _USERMODELRESPONSE_ERROR,
    '__module__' : 'um_server_pb2'
    # @@protoc_insertion_point(class_scope:um_server.UserModelResponse.Error)
    })
  ,
  'DESCRIPTOR' : _USERMODELRESPONSE,
  '__module__' : 'um_server_pb2'
  # @@protoc_insertion_point(class_scope:um_server.UserModelResponse)
  })
_sym_db.RegisterMessage(UserModelResponse)
_sym_db.RegisterMessage(UserModelResponse.Error)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'um_server_pb2'
  # @@protoc_insertion_point(class_scope:um_server.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {

  'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
    'DESCRIPTOR' : _UPDATERESPONSE_ERROR,
    '__module__' : 'um_server_pb2'
    # @@protoc_insertion_point(class_scope:um_server.UpdateResponse.Error)
    })
  ,
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'um_server_pb2'
  # @@protoc_insertion_point(class_scope:um_server.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)
_sym_db.RegisterMessage(UpdateResponse.Error)


DESCRIPTOR._options = None

_USERMODELSERVICE = _descriptor.ServiceDescriptor(
  name='UserModelService',
  full_name='um_server.UserModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=664,
  serialized_end=814,
  methods=[
  _descriptor.MethodDescriptor(
    name='search',
    full_name='um_server.UserModelService.search',
    index=0,
    containing_service=None,
    input_type=_USERMODELREQUEST,
    output_type=_USERMODELRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='um_server.UserModelService.update',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERMODELSERVICE)

DESCRIPTOR.services_by_name['UserModelService'] = _USERMODELSERVICE

# @@protoc_insertion_point(module_scope)
