# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_info_pb2 as item__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_info.proto',
  package='user_info',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fuser_info.proto\x12\tuser_info\x1a\x0fitem_info.proto\"\xbe\x03\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\r\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x11\n\teducation\x18\x06 \x01(\t\x12\x12\n\nlife_stage\x18\x07 \x01(\t\x12\x15\n\rconstellation\x18\x08 \x01(\t\x12\x0f\n\x07\x63ompany\x18\t \x01(\t\x12\x12\n\ndepartment\x18\n \x01(\t\x12\r\n\x05\x65mail\x18\x0b \x01(\t\x12\x0b\n\x03job\x18\x0c \x01(\t\x12%\n\x0blong_topics\x18\r \x03(\x0b\x32\x10.item_info.Topic\x12&\n\x0cshort_topics\x18\x0e \x03(\x0b\x32\x10.item_info.Topic\x12)\n\x0fselected_topics\x18\x0f \x03(\x0b\x32\x10.item_info.Topic\x12!\n\tlong_tags\x18\x10 \x03(\x0b\x32\x0e.item_info.Tag\x12\"\n\nshort_tags\x18\x11 \x03(\x0b\x32\x0e.item_info.Tag\x12 \n\x06\x65vents\x18\x12 \x03(\x0b\x32\x10.user_info.Event\"\x99\x01\n\x05\x45vent\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\'\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x17.user_info.Event.Action\x12\x12\n\nstart_time\x18\x04 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\r\" \n\x06\x41\x63tion\x12\t\n\x05\x43LICK\x10\x00\x12\x0b\n\x07\x43OLLECT\x10\x01\"\xe3\x01\n\x15\x45ventForProfileUpdate\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x37\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\'.user_info.EventForProfileUpdate.Action\x12\x12\n\nstart_time\x18\x04 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\r\x12(\n\x0etopic_category\x18\x06 \x01(\x0b\x32\x10.item_info.Topic\" \n\x06\x41\x63tion\x12\t\n\x05\x43LICK\x10\x00\x12\x0b\n\x07\x43OLLECT\x10\x01\x62\x06proto3'
  ,
  dependencies=[item__info__pb2.DESCRIPTOR,])



_EVENT_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='user_info.Event.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLICK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=618,
  serialized_end=650,
)
_sym_db.RegisterEnumDescriptor(_EVENT_ACTION)

_EVENTFORPROFILEUPDATE_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='user_info.EventForProfileUpdate.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLICK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=618,
  serialized_end=650,
)
_sym_db.RegisterEnumDescriptor(_EVENTFORPROFILEUPDATE_ACTION)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='user_info.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='user_info.UserInfo.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='user_info.UserInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='user_info.UserInfo.nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='user_info.UserInfo.age', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='user_info.UserInfo.gender', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='education', full_name='user_info.UserInfo.education', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='life_stage', full_name='user_info.UserInfo.life_stage', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='constellation', full_name='user_info.UserInfo.constellation', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='user_info.UserInfo.company', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department', full_name='user_info.UserInfo.department', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='user_info.UserInfo.email', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job', full_name='user_info.UserInfo.job', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_topics', full_name='user_info.UserInfo.long_topics', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_topics', full_name='user_info.UserInfo.short_topics', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selected_topics', full_name='user_info.UserInfo.selected_topics', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_tags', full_name='user_info.UserInfo.long_tags', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='short_tags', full_name='user_info.UserInfo.short_tags', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='user_info.UserInfo.events', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=494,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='user_info.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_id', full_name='user_info.Event.log_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='user_info.Event.item_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='user_info.Event.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='user_info.Event.start_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='user_info.Event.end_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=650,
)


_EVENTFORPROFILEUPDATE = _descriptor.Descriptor(
  name='EventForProfileUpdate',
  full_name='user_info.EventForProfileUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_id', full_name='user_info.EventForProfileUpdate.log_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='user_info.EventForProfileUpdate.item_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='user_info.EventForProfileUpdate.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='user_info.EventForProfileUpdate.start_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='user_info.EventForProfileUpdate.end_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_category', full_name='user_info.EventForProfileUpdate.topic_category', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTFORPROFILEUPDATE_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=880,
)

_USERINFO.fields_by_name['long_topics'].message_type = item__info__pb2._TOPIC
_USERINFO.fields_by_name['short_topics'].message_type = item__info__pb2._TOPIC
_USERINFO.fields_by_name['selected_topics'].message_type = item__info__pb2._TOPIC
_USERINFO.fields_by_name['long_tags'].message_type = item__info__pb2._TAG
_USERINFO.fields_by_name['short_tags'].message_type = item__info__pb2._TAG
_USERINFO.fields_by_name['events'].message_type = _EVENT
_EVENT.fields_by_name['action'].enum_type = _EVENT_ACTION
_EVENT_ACTION.containing_type = _EVENT
_EVENTFORPROFILEUPDATE.fields_by_name['action'].enum_type = _EVENTFORPROFILEUPDATE_ACTION
_EVENTFORPROFILEUPDATE.fields_by_name['topic_category'].message_type = item__info__pb2._TOPIC
_EVENTFORPROFILEUPDATE_ACTION.containing_type = _EVENTFORPROFILEUPDATE
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventForProfileUpdate'] = _EVENTFORPROFILEUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:user_info.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:user_info.Event)
  })
_sym_db.RegisterMessage(Event)

EventForProfileUpdate = _reflection.GeneratedProtocolMessageType('EventForProfileUpdate', (_message.Message,), {
  'DESCRIPTOR' : _EVENTFORPROFILEUPDATE,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:user_info.EventForProfileUpdate)
  })
_sym_db.RegisterMessage(EventForProfileUpdate)


# @@protoc_insertion_point(module_scope)
